# Generated by Django 4.1.1 on 2022-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, choices=[('size_1-9', '1-9'), ('size_10-49', '10-49'), ('size_50-99', '50-99'), ('size_100', '100+')], default='size_1-9', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.DateTimeField(),
        ),
    ]
