# Generated by Django 4.1.1 on 2022-09-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_deadline_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
